//
//  RotationCircle.h
//  RotationCircle
//
//  Created by tangxianhai on 15/8/5.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface RotationCircle : NSObject

// Generated Images
+ (UIImage*)imageOfCanvas1WithCircleRect: (CGRect)circleRect;

@end
